#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ "${LQXP_ANDROID_BUILD_RUNNING:-}" == "1" ]]; then
  echo "error: refusing to recursively run scripts/build-android.sh." >&2
  exit 1
fi

if [[ "${IN_NIX_SHELL:-}" != "pure" && "${IN_NIX_SHELL:-}" != "impure" ]]; then
  if command -v nix >/dev/null 2>&1 && [[ -f flake.nix ]]; then
    echo "Entering nix develop for Android build..."
    exec nix develop --command env LQXP_ANDROID_BUILD_RUNNING=1 scripts/build-android.sh "$@"
  elif command -v nix-shell >/dev/null 2>&1 && [[ -f shell.nix ]]; then
    echo "Entering nix-shell for Android build..."
    printf -v quoted_args "%q " "$@"
    exec nix-shell --run "LQXP_ANDROID_BUILD_RUNNING=1 scripts/build-android.sh ${quoted_args}"
  fi

  echo "warning: not running inside nix-shell/nix develop, continuing with the current environment." >&2
fi

command -v bun >/dev/null 2>&1 || {
  echo "error: bun is required." >&2
  exit 1
}

command -v rustup >/dev/null 2>&1 || {
  echo "error: rustup is required." >&2
  exit 1
}

export RUSTUP_TOOLCHAIN="${RUSTUP_TOOLCHAIN:-stable}"
export TMPDIR="/tmp"
export LQXP_RUSTUP_BIN_DIR="/tmp/lqxp-client-rustup-bin-${UID:-$(id -u)}"
mkdir -p "$LQXP_RUSTUP_BIN_DIR"

cat > "$LQXP_RUSTUP_BIN_DIR/cargo" <<'EOF'
#!/usr/bin/env bash
exec rustup run "${RUSTUP_TOOLCHAIN:-stable}" cargo "$@"
EOF

cat > "$LQXP_RUSTUP_BIN_DIR/rustc" <<'EOF'
#!/usr/bin/env bash
exec rustup run "${RUSTUP_TOOLCHAIN:-stable}" rustc "$@"
EOF

chmod +x "$LQXP_RUSTUP_BIN_DIR/cargo" "$LQXP_RUSTUP_BIN_DIR/rustc"
export PATH="$LQXP_RUSTUP_BIN_DIR:$PATH"
export CARGO="$LQXP_RUSTUP_BIN_DIR/cargo"
export RUSTC="$LQXP_RUSTUP_BIN_DIR/rustc"
hash -r 2>/dev/null || true

command -v cargo >/dev/null 2>&1 || {
  echo "error: cargo is required." >&2
  exit 1
}

if [[ -z "${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}" ]]; then
  echo "error: ANDROID_SDK_ROOT/ANDROID_HOME is not set. Run through nix-shell or nix develop." >&2
  exit 1
fi

if [[ -z "${ANDROID_NDK_ROOT:-${ANDROID_NDK_HOME:-${NDK_HOME:-}}}" ]]; then
  echo "error: ANDROID_NDK_ROOT/ANDROID_NDK_HOME/NDK_HOME is not set. Run through nix-shell or nix develop." >&2
  exit 1
fi

if declare -F lqxp-rustup-android-targets >/dev/null 2>&1; then
  lqxp-rustup-android-targets
else
  rustup toolchain install "$RUSTUP_TOOLCHAIN" --profile minimal
  rustup target add --toolchain "$RUSTUP_TOOLCHAIN" \
    aarch64-linux-android \
    armv7-linux-androideabi \
    i686-linux-android \
    x86_64-linux-android
fi

if [[ ! -d src-tauri/gen/android || "${LQXP_FORCE_ANDROID_INIT:-}" == "1" ]]; then
  bun tauri android init
fi

local_properties="src-tauri/gen/android/local.properties"
if [[ ! -f "$local_properties" || "${LQXP_REWRITE_ANDROID_LOCAL_PROPERTIES:-}" == "1" ]]; then
  {
    echo "# Generated by scripts/build-android.sh"
    echo "sdk.dir=${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
    echo "ndk.dir=${ANDROID_NDK_ROOT:-${ANDROID_NDK_HOME:-$NDK_HOME}}"
    if [[ -n "${CMAKE_ROOT:-}" ]]; then
      echo "cmake.dir=$CMAKE_ROOT"
    fi
  } > "$local_properties"
fi

bun install --no-save
(cd QxpClient && bun install --no-save)

build_args=("$@")
if [[ ${#build_args[@]} -eq 0 ]]; then
  build_args=(--debug --apk)
fi

bun tauri android build "${build_args[@]}"

echo
echo "APK output(s):"
find src-tauri/gen/android/app/build/outputs -name "*.apk" -print 2>/dev/null || true
